[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[users]

    [users.louis]
    id = "111111111111111"
    prefix = "louis said"
    image = "src/louis.jpg"
    width = 400
    height = 250
    x = 40
    y = 30